# 集群部署 6800/6801互相注册
server:
  port: ${port:6800} #指定访问端口
spring:
  application:
    name: eureka-server #指定服务名
eureka:
  client:
    register-with-eureka: true #是否将自己注册到Eureka服务中，默认为true
    fetch-registry: true #是否从Eureka中获取注册信息
    service-url: #Eureka客户端与服务端交互的地址，这里集群部署eureka-server
      defaultZone: http://example:123456@192.168.0.239:${oport:6801}/eureka/
  instance:
    ip-address: 192.168.0.239
security:
  basic: #开启基于HTTP basic的安全验证
    enabled: true 
  user: #配置用户账户信息
    name: example
    password: 123456